### ISSUE TITLE
DESIGN TODO'S

### ISSUE THREAD

**Issue by oskarsmartinsons** [UnofficialHenry/Lingo#2]
## Blueprint interface  (visual) - Liene
- [x] start / end part of the game 
- [x] Color scheme 
- [x] Layout 

##  FRONT END: - Oskars
- [x] start / end part of the game 
- [x] Responsive WEB Design
- [x] Mobile support
- [x] Supported browsers

## BACK END:  - Gustavs
- [x] web client, web server, web resource,  database relationships - description - GUSTAVS
- [x] ARCHITECTURE of APPLICATION – web client, web server, web resource,   - GUSTAVS
